// <auto-generated />
using System;
using ABtest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ABtest.Migrations
{
    [DbContext(typeof(PostgreeSqlContext))]
    [Migration("20211023064641_AddUserLifespanColumn")]
    partial class AddUserLifespanColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ABtest.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateLastActivity")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("Date");

                    b.Property<double>("LifespanInDays")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasComputedColumnSql("\"DateLastActivity\" - \"DateRegistration\"", true);

                    b.HasKey("UserID");

                    b.HasIndex("LifespanInDays");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
